projects:
  afisha_restaurants:
    display_name: Афиша.Рестораны
    appstore_id: '916815434'
    bundle_id: com.afisha.restaurants
    fabric_project_id: '559fcdc393fece3d9400001a'

  afisha:
    display_name: Афиша
    appstore_id: '323214038'
    bundle_id: ru.afisha.iphone
    fabric_project_id: '551d4e9e893cfa3fe800004a'